module.exports = {
  classic: {
    1: 'Boulevard de Belleville',
    3: 'Rue Lecourbe',
    5: 'Rue de Vaugirard',
    6: 'Rue de Courcelles',
    8: 'Avenue de la République',
    10: 'Boulevard de la Villette',
    11: 'Avenue de Neuilly',
    13: 'Rue de Paradis',
    14: 'Gare de Lyon',
    15: 'Avenue Mozart',
    17: 'Boulevard Saint-Michel',
    18: 'Place Pigalle',
    20: 'Avenue Matignon',
    22: 'Boulevard Malesherbes',
    23: 'Avenue Henri-Martin',
    24: 'Gare du Nord',
    25: 'Faubourg Saint-Honoré',
    26: 'Place de la Bourse',
    27: 'Compagnie des Eaux',
    28: 'Rue La Fayette',
    30: 'Avenue de Breteuil',
    31: 'Avenue Foch',
    33: 'Boulevard des Capucines',
    34: 'Gare Saint-Lazare',
    36: 'Avenue des Champs-Élysées',
    38: 'Rue de la Paix'
  },
  english: {
    1: 'Old Kent Road',
    3: 'Whitechapel Road',
    5: 'The Angel Islington',
    6: 'Euston Road',
    8: 'Pentonville Road',
    10: 'Pall Mall',
    11: 'Whitehall',
    13: 'Northumberland Avenue',
    14: 'Marylebone Station',
    15: 'Bow Street',
    17: 'Marlborough Street',
    18: 'Vine Street',
    20: 'Strand',
    22: 'Fleet Street',
    23: 'Trafalgar Square',
    24: 'Fenchurch St Station',
    25: 'Leicester Square',
    26: 'Coventry Street',
    27: 'Water Works',
    28: 'Piccadilly',
    30: 'Regent Street',
    31: 'Oxford Street',
    33: 'Bond Street',
    34: 'Liverpool St Station',
    36: 'Park Lane',
    38: 'Mayfair'
  }
};
